[build]
target = "riscv64imac-unknown-none-elf"

[target.riscv64imac-unknown-none-elf]
rustflags = [
    "-C", "force-unwind-tables=no",
    "-C", "code-model=medium",
    "-C", "target-feature=-c",
]

