[package]
name = "vm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
elf = "0.8.0"
thiserror = "2.0.17"
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1.7"
