name: Release Kernel
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Next Version (e.g. v1.0.0). Check Releases for last version.'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release-kernel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: riscv64gc-unknown-none-elf

      - name: Run build script
        run: cargo build -p kernel --target riscv64gc-unknown-none-elf --release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: kernel-${{ inputs.version }}
          name: Kernel ${{ inputs.version }}
          files: target/riscv64gc-unknown-none-elf/release/kernel
          generate_release_notes: true

